categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
read_more: Read More