index: Index
categories: Categories
category: "Category: "
search: Search
tags: Tags
tag: "Tag: "
prev: Prev
next: Next
comment: Comments
archives: Archives
recent_posts: Recent Posts
links: Links
gallery: Gallery
read_more: Read More
latest: Latest
earliest: Earliest
quiz:
  choice: Multiple Choice
  multiple: Multiple Answer
  true_false: True/False
  essay: Questions
  gap_fill: Gap Filling
  mistake: Wrong Answer